#!/bin/bash

# Ensure there are no changes to be pushed
if [[ `git status --porcelain` ]]; then
	echo ""
	echo "There are uncommited changes. Please commit them or something."
	exit 1
fi

# Run the test suite
venv/bin/python test/test_runner.py
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo ""
	echo "Failed tests. Code will not be deployed until all tests are resolved"
	exit $RESULT
fi

# Zip and update the code for the Lambda
cd src
../venv/bin/pip install -r ../requirements.txt -t .
zip -r lambda.zip *
aws lambda update-function-code --function-name pickleball-pro-ws --zip-file fileb://lambda.zip --profile personal
git status | grep '\t' | xargs -I {} rm -r {}
cd ..
